--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/David-pm-pl/MultiServerChat
build-by-default: true
branches:
- stable
projects:
  MultiServerChat:
    path: ""
    icon: "assets/images/icon.png"
...
